# This is a basic workflow to help you get started with Actions

name: Mattermost_message

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Mitigram/gh-action-mattermost@main
      with:
          username: t8y
          url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          text: Update in develop

